### ISSUE TITLE
Empty value in Grafana variables

### ISSUE THREAD

**Issue by Heyzi** [VictoriaMetrics/victorialogs-datasource#159]
A simple query also returns an empty value, which should be filtered out.
```
grafana:11.4.0
victorialogs-datasource-v0.12.0
```

<img width="1326" alt="image" src="https://github.com/user-attachments/assets/6be7b69e-5244-46fe-863a-ba698f095709" />
<img width="699" alt="image" src="https://github.com/user-attachments/assets/192ca84f-b94e-4582-95f3-b517fee711a9" />

The logs are collected using vector with the following configuration:
```
  logs_system_to_loki:
    type: loki
    inputs:
      - journald_transform
    endpoint: "http://......./insert/loki/"
    path: /api/v1/push
    encoding:
      codec: json
    labels:
      job: 'journald'
      unit: "{{ unit }}"
      server_name: "{{ server_name }}"
    healthcheck:
      enabled: false
```
