### ISSUE TITLE
Installation error provided version doesn't use semantic versioning

### ISSUE THREAD

**Issue by xente** [VictoriaMetrics/victorialogs-datasource#169]
Hi,
I am trying to instal the module into bitnami/grafana-operator version 4.9.0

**Configuration:**

```
grafana:
  extraEnvVars:
    - name: GF_INSTALL_PLUGINS
      value: https://github.com/VictoriaMetrics/victorialogs-datasource/releases/download/v0.13.0/victoriametrics-logs-datasource-v0.13.0.zip;victoriametrics-logs-datasource
    - name: GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS
      value: victoriametrics-logs-datasource
```

**Error**
grafana INFO ==> Installing plugin https @ //github.com/VictoriaMetrics/victorialogs-datasource/releases/download/v0.13.0/victoriametrics-logs-datasource-v0.13.0.zip
The provided version doesn't use semantic versioning format

Error: ✗ 404: Plugin not found

Same issue using older plugin version and older version of helm chart
