### ISSUE TITLE
Add option to define log levels in grafana datasources yaml file (if possible)

### ISSUE THREAD

**Issue by docentYT** [VictoriaMetrics/victorialogs-datasource#315]
This plugin has the ability to set `Log level rules`.  However, it requires manually setting it in the UI. Is it possible to make level rules setable in the [datasources yaml](https://grafana.com/docs/grafana/latest/administration/provisioning/)?

**Comment by Loori-R** [comment]
We’ll add a description to the documentation — for now, you can define log level rules in your data source configuration like this:

```yaml
datasources:
  - name: 'VictoriaLogs'
    type: 'victoriametrics-logs-datasource'
    access: proxy
    isDefault: false
    orgId: 1
    version: 1
    editable: true
    jsonData:
      logLevelRules:
        - field: statusCode
          operator: greaterThan
          value: 500
          level: critical
          enabled: true
```

Allowed Values:
**Levels:** `critical`, `error`, `warning`, `info`, `debug`, `trace`, `unknown`
**Operators:** `equals`, `notEquals`, `greaterThan`, `lessThan`, `regex`
