### ISSUE TITLE
config for grafana-operator is wrong.

### ISSUE THREAD

**Issue by ThomasADavis** [VictoriaMetrics/victorialogs-datasource#32]
The config listed in the docs for grafana operator is wrong, and will generate an read-only error.

I succeeded in getting it to install by doing this:

```
            - name: "load-vl-ds-plugin"
              image: "curlimages/curl:7.85.0"
              command: [ "/bin/sh" ]
              workingDir: "/var/lib/grafana"
              securityContext:
                runAsUser: 472
                runAsNonRoot: true
                runAsGroup: 472
              args:
                - "-c"
                - |
                  set -ex
                  mkdir -p /var/lib/grafana/plugins/
                  ver=$(curl -s https://api.github.com/repos/VictoriaMetrics/victorialogs-datasource/releases/latest | grep -oE 'v[0-9]+\.[0-9]+\.[0-9]+' | head -1)
                  curl -L https://github.com/VictoriaMetrics/victorialogs-datasource/releases/download/$ver/victorialogs-datasource-$ver.tar.gz -o /var/lib/grafana/plugins/vl-ds-plugin.tar.gz
                  tar -xf /var/lib/grafana/plugins/vl-ds-plugin.tar.gz -C /var/lib/grafana/plugins/
                  rm /var/lib/grafana/plugins/vl-ds-plugin.tar.gz
              volumeMounts:
                - name: grafana-data
                  mountPath: /var/lib/grafana
```

note the runAs changes.  I also changed the tar file from plugin.tar.gz to vl-ds-plugin.tar.gz to avoid collisions with the vm datasource plugin.
